providers:
  - nixpacks

phases:
  setup:
    nixPkgs:
      - nodejs_20
      - npm-10_x
      - python3
  install:
    cmds:
      - npm ci
  build:
    cmds:
      - npm run build

start:
  cmd: node server/index.js
